### ISSUE TITLE
attempting to get this working on jupyterlab

### ISSUE THREAD

**Issue by Analect** [alan0201tw/JupyterNotebook_auto_pop_GUI#1]
@alan0201tw ... I happened upon your novel solution to get a git workflow working in conjunction with jupyter. I tried to get it working in conjunction with jupyterlab, but failed.  I expect it has something to do with the fact that the notebook is wrapped within phosphor rather than being exposed directly to the browser.

I was wondering if it might be viable to make this into a jupyterlab extension instead ... something akin to what has been done with [jupyterlab-hub](https://github.com/jupyterhub/jupyterlab-hub), which ends up adding menu items within jupyterlab ... in this case to navigate back to a jupyerhub menu or to log out. 

A modified version of this tool might expose a git menu ... for interaction back to a remote git repository.

**Comment by alan0201tw** [comment]
Hi , @Analect , thanks for pointing out the problem.
I might update some codes in the future but this repository is currently not maintained because I'm simply too busy on my school studies.
If you happened to successfully solve the problem, please let me know!
And sorry for not being able to help.

**Comment by Analect** [comment]
Thanks @alan0201tw  .. will let you know if I make any progress.
